#!/usr/bin/env python3

import sys
import argparse
import se
import se.formatting


def main() -> int:
	parser = argparse.ArgumentParser(description="Convert a fragment of MathML into a transparent PNG. Output is saved to the specified filename.")
	parser.add_argument("-o", "--output-filename", dest="output_filename", metavar="FILENAME", required=True, type=str, help="the filename to save PNG output to")
	parser.add_argument("mathml_fragment", metavar="FRAGMENT", help="a fragment of MathML; for example: <math><mi>x</mi></math>")
	args = parser.parse_args()

	try:
		se.formatting.render_mathml_to_png(args.mathml_fragment, args.output_filename)
	except se.SeException as ex:
		se.print_error(ex)
		return ex.code

	return 0


if __name__ == "__main__":
	sys.exit(main())
